version: "3.9"
services:
  deploy:
    container_name: javaUserApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localPostgresSQLDB:5432/userservice_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
